// <auto-generated />
using System;
using IGTI.gabrielmoutinho.demoacmeap.API.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace IGTI.gabrielmoutinho.demoacmeap.API.Migrations
{
    [DbContext(typeof(APIDbContext))]
    [Migration("20210316234020_InitialDatabase")]
    partial class InitialDatabase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.4");

            modelBuilder.Entity("IGTI.gabrielmoutinho.demoacmeap.API.Models.Cliente", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CPF")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("TEXT")
                        .HasColumnName("Data_Nascimento");

                    b.Property<long?>("Id_Endereco")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Id_Endereco");

                    b.ToTable("Cliente");
                });

            modelBuilder.Entity("IGTI.gabrielmoutinho.demoacmeap.API.Models.Endereco", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Bairro")
                        .HasColumnType("TEXT");

                    b.Property<string>("Cidade")
                        .HasColumnType("TEXT");

                    b.Property<string>("Logradouro")
                        .HasColumnType("TEXT");

                    b.Property<int>("Numero")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UF")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Endereco");
                });

            modelBuilder.Entity("IGTI.gabrielmoutinho.demoacmeap.API.Models.Fatura", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Codigo")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataLeitura")
                        .HasColumnType("TEXT")
                        .HasColumnName("Data_Leitura");

                    b.Property<DateTime>("DataVencimento")
                        .HasColumnType("TEXT")
                        .HasColumnName("Data_Vencimento");

                    b.Property<long?>("Id_Instalacao")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumeroLeitura")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Numero_Leitura");

                    b.Property<float>("ValorConta")
                        .HasColumnType("REAL")
                        .HasColumnName("Valor_Conta");

                    b.HasKey("Id");

                    b.HasIndex("Id_Instalacao");

                    b.ToTable("Fatura");
                });

            modelBuilder.Entity("IGTI.gabrielmoutinho.demoacmeap.API.Models.Instalacao", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Codigo")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataInstalacao")
                        .HasColumnType("TEXT")
                        .HasColumnName("Data_Instalacao");

                    b.Property<long?>("Id_Cliente")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("Id_Endereco")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Id_Cliente");

                    b.HasIndex("Id_Endereco");

                    b.ToTable("Instalacao");
                });

            modelBuilder.Entity("IGTI.gabrielmoutinho.demoacmeap.API.Models.Cliente", b =>
                {
                    b.HasOne("IGTI.gabrielmoutinho.demoacmeap.API.Models.Endereco", "Endereco")
                        .WithMany()
                        .HasForeignKey("Id_Endereco");

                    b.Navigation("Endereco");
                });

            modelBuilder.Entity("IGTI.gabrielmoutinho.demoacmeap.API.Models.Fatura", b =>
                {
                    b.HasOne("IGTI.gabrielmoutinho.demoacmeap.API.Models.Instalacao", "Instalacao")
                        .WithMany("Fatura")
                        .HasForeignKey("Id_Instalacao");

                    b.Navigation("Instalacao");
                });

            modelBuilder.Entity("IGTI.gabrielmoutinho.demoacmeap.API.Models.Instalacao", b =>
                {
                    b.HasOne("IGTI.gabrielmoutinho.demoacmeap.API.Models.Cliente", "Cliente")
                        .WithMany("Instalacao")
                        .HasForeignKey("Id_Cliente");

                    b.HasOne("IGTI.gabrielmoutinho.demoacmeap.API.Models.Endereco", "Endereco")
                        .WithMany()
                        .HasForeignKey("Id_Endereco");

                    b.Navigation("Cliente");

                    b.Navigation("Endereco");
                });

            modelBuilder.Entity("IGTI.gabrielmoutinho.demoacmeap.API.Models.Cliente", b =>
                {
                    b.Navigation("Instalacao");
                });

            modelBuilder.Entity("IGTI.gabrielmoutinho.demoacmeap.API.Models.Instalacao", b =>
                {
                    b.Navigation("Fatura");
                });
#pragma warning restore 612, 618
        }
    }
}
